Algoritmo "semnome"

Var
 dia, mes, ano, diasdevida: real


Inicio
      escreva("Digite o dia do seu nascimento: ")
      leia(dia)
      escreva("Digite o mes do seu nascimento: ")
      leia(mes)
      escreva("Digite o ano do seu nascimento: ")
      leia(ano)
      ano <- 2022-ano
      escreval("Sua idade e ", ano)
      diasdevida <- dia+(mes*30)+(ano*365)
      escreva("Voce tem ", diasdevida, " dias de vida")
      


Fimalgoritmo